version: '3.8'
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      #- PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      # <Puerto expuesto> : < Puerto dentro del container>
      # Solo para desarrollo. Comentar en produccion
      - '5432:5432'
    expose:
      # Abre el puerto 5432 en el container al exterior sin tocar nada de la configuración del postgresql
      # Solo para desarrollo. Comentar en produccion        
      - '5432'
    restart: always             # run as a service
  odoo13:
    image: odoo:15.0
    container_name: odoo15
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    command: -- --dev=reload
    # command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
  pgadmin:
    image: dpage/pgadmin4:6.14
    container_name: pgadmin4
    restart: always
    environment:
       PGADMIN_DEFAULT_EMAIL: ikbdy@plaiaundi.net
       PGADMIN_DEFAULT_PASSWORD: ikbdy
       PGADMIN_LISTEN_PORT: 80
    ports:
       - "8080:80"
    links:
       - "db:pgsql-server"
